version: "3.7"
services:

  fastapi:
    build:
      context: ./client-side/fastapi
      dockerfile: dockerfile
    ports:
      - '80:80'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - document-streaming

  spark:
    image: 'jupyter/pyspark-notebook:spark-2'
    ports:
      - '8888:8888'
      - "4040-4080:4040-4080"
    volumes:
      - ./apacheSpark:/home/jovyan/work
    networks:
      - document-streaming

  zookeeper:
    image: 'bitnami/zookeeper:3.7.0-debian-10-r70'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - document-streaming

  kafka:
    image: 'bitnami/kafka:2.8.0-debian-10-r42'
    ports:
      - '9093:9093'          #change to 9093 to access external from your windows host
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT     #add aditional listener for external
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093                              #9092 will be for other containers, 9093 for your windows client
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093     #9092 will be for other containers, 9093 for your windows client
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
    networks:
      - document-streaming

  mongo:
    container_name: mongo-dev
    image: mongo
    restart: on-failure
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: duycao  
      MONGO_INITDB_ROOT_PASSWORD: 123
      MONGO_INITDB_DATABASE: streaming
    networks:
      - document-streaming

  mongo-express:
    image: mongo-express
    restart: on-failure
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-dev
      ME_CONFIG_MONGODB_ADMINUSERNAME: duycao
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: tribes
    networks:
      - document-streaming
    depends_on:
      - mongo
  
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      # POSTGRES_USER: postgres
    networks:
      - document-streaming

  pgadmine4:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: caovanduy3108@gmail.com
      PGADMIN_DEFAULT_PASSWORD: example
    networks:
      - document-streaming


networks:
  document-streaming:
    driver: bridge